version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: on-failure:5
    env_file:
      - .env
    volumes:
      - ${CONTAINER_WORKSPACE-.}/${CONTAINER_NAME-gitea}/gitea/lib:/var/lib/gitea
      - ${CONTAINER_WORKSPACE-.}/${CONTAINER_NAME-gitea}/gitea/config:/etc/gitea
      - ${CONTAINER_WORKSPACE-.}/${CONTAINER_NAME-gitea}/gitea/data:/data
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: curl -fSs 127.0.0.1:3000/api/v1/health | grep "Found" || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - ${NETWORK-bridge}
    ports:
      - ${OPEN_GITEA_PORT-3000}:3000
      - ${OPEN_SSH_PORT-2222}:2222
    depends_on:
      - postgres

  postgres:
    env_file:
      - .env
    #volumes:
    #  - ${CONTAINER_WORKSPACE-.}/${CONTAINER_NAME-gitea}/postgres/data:/var/lib/postgresql/data
    networks:
      - ${NETWORK-bridge}
    extends:
      file: ../postgres/docker-compose.yml
      service: postgres
    ports:
      - ${OPEN_PROSTGRES_PORT-5432}:5432

networks:
  gitea:
    driver: bridge
