version: "3.1"

services:
  mysql:
    env_file:
      - .env
    image: mysql:latest
    container_name: mysql
    restart: on-failure:5
    healthcheck:
      test: mysqladmin --host=127.0.0.1 --port=${OPEN_PORT-3306} --user=$MYSQL_USER --password=$MYSQL_PASSWORD ping
      interval: 15s
      timeout: 5s
      retries: 3
    volumes:
      - ${CONTAINER_WORKSPACE-.}/${NAME-mysql}/data:/var/lib/mysql
    ports:
      - ${OPEN_PORT-3306}:3306
