version: "3.1"

services:
  postgres:
    env_file:
      - .env
    image: postgres:latest
    container_name: postgres
    restart: on-failure:5
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "--host=postgres",
          "--dbname=$POSTGRES_DB",
          "--username=$POSTGRES_USER",
        ]
      interval: 15s
      timeout: 5s
      retries: 3
    volumes:
      - ${CONTAINER_WORKSPACE-.}/${NAME-postgres}/data:/var/lib/postgresql/data
    #ports:
    #- "5432:5432"
