version: "3.1"

services:
  postgres:
    env_file:
      - .env
    image: postgres:latest
    container_name: postgres
    restart: on-failure:5
    healthcheck:
      test: pg_isready --host=127.0.0.1 --port=${OPEN_PORT-5432} --dbname=$POSTGRES_DB --username=$POSTGRES_USER
      interval: 15s
      timeout: 5s
      retries: 3
    volumes:
      - ${CONTAINER_WORKSPACE-.}/${NAME-postgres}/data:/var/lib/postgresql/data
    ports:
      - ${OPEN_PORT-5432}:5432
