version: "3.1"

services:
  redis:
    env_file:
      - .env
    image: redis:latest
    container_name: redis
    restart: on-failure:5
    healthcheck:
      test: redis-cli --no-auth-warning -a ${REDIS_PASSWORD-} ping | grep "PONG" || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
    command: redis-server --requirepass ${REDIS_PASSWORD-}
    volumes:
      - ${CONTAINER_WORKSPACE-.}/${NAME-postgres}/data:/data
    ports:
      - ${OPEN_PORT-6379}:6379
